config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'articles#last_active'
  get '/admin', to: 'articles#edit'
  post '/admin', to: 'articles#create'
  patch '/admin', to: 'articles#update'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  scope :from_yandex, -> { where(expired_at: nil).order(:created_at) }

  validates_presence_of :title, :annotation
  validates_datetime :expired_at, on_or_after: :now, allow_nil: true

  after_save :broadcast_last_active

  def self.custom
    find_by('expired_at >= ?', Time.now)
  end

  def self.last_active
    custom || from_yandex.last
  end

  def custom?
    return false unless expired_at
    expired_at >= Time.now
  end

  private

  def broadcast_last_active
    article = self.class.last_active
    if article
      ActionCable.server.broadcast('last_article',
                                   title: article.title,
                                   annotation: article.annotation,
                                   created_at: created_at,
                                   expired_at: article.expired_at)

      if article.custom?
        # download new yandex article
        # when it will be saved, broadcast_last_active method will be raised
        # and it will change custom article to yandex one in opened pages
        YandexArticleDownloadJob.set(wait_until: article.expired_at + 1.second)
                                .perform_later
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_custom_or_new_article, only: %i(edit update)

  def last_active
    @article = Article.last_active
  end

  def edit
  end

  def create
    @article = Article.new article_params

    if @article.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def update
    if @article.update(article_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def set_custom_or_new_article
    @article = (Article.custom || Article.new)
  end

  def article_params
    params.require(:article).permit(:title, :annotation, :expired_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def humanized_datetime(datetime)
    return nil if datetime.nil?
    datetime.in_time_zone('Moscow').strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true, url: '/admin') do |form| %>
  <% if article.errors.any? %>
    <div class="article-item">
      <p><%= article.errors.full_messages.join('. ')%></li></p>
    </div>
  <% end %>

  <div class="field article-item">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title %>
  </div>

  <div class="field article-item">
    <%= form.label :annotation %>
    <%= form.text_field :annotation, id: :article_annotation %>
  </div>

  <div class="field article-item">
    <%= form.label :expired_at %>
    <%= form.datetime_select :expired_at, id: :article_expired_at %>
  </div>

  <div class="actions article-item">
    <%= form.submit 'Сохранить' %>
    <%= link_to 'Отменить', root_path %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="flex-container">
  <div class="flex-row">
    <h3 class="article-item">Изменить авторскую новость</h3>

    <%= render 'form', article: @article %>
  </div>
</div>

app/views/articles/last_active.html.erb
<div class="flex-container">
  <div class="flex-row">
    <h3 class="article-item" id="article-title"><%= @article&.title %></h3>
    <p class="article-item" id="article-annotation"><%= @article&.annotation %></p>
    <p class="article-item" id="article-creation-date"><%= humanized_datetime(@article&.created_at) %></p>

    <br>
    <div class="article-item">
      <%= link_to('Изменить авторскую новость', admin_path) %>
    <div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YandexNews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>